### PR TITLE
Add ability to show counter in the status label

### PR DESCRIPTION
**Pull request by DaveMDS**
Hey, 
this PR add a simple option to enable the visualization of the counter value "live" in the node status label, really useful while debugging your flows.
hope you like the idea :)

### CODE REVIEW

**Comment by eisbehr-** [comment]
Hello @DaveMDS 

Nice idea. Could be useful. I haven't tested it yet, but it looks fine what i see. Only thing i would change is the label `Counter` for the option. The node is already named like this, so a `counter` node with the option `counter` is a bit confusing.

Maybe i'll find a solution for that. ;)

**Comment by DaveMDS** [comment]
Indeed, I'm also not super happy with the label name (nor for the option name "show")
but no other better terms on my mind atm...feel free to change as you like ;)

As you liked this one I'm also going to propose you a second feature for the stat that I would like to implement:
the idea is to also set the stat icon to 'gray' and, when a msg arrive, change the icon to 'blue' for 3 seconds, then back to gray. This way you can also see when the value arrive or if it changed moments ago.

Infact this is my current usage of Counter:
counter
The "trigger 2s" is there to show the blue dot for X seconds when a msg arrive, it would be cool
to integrate it inside counter, so every time the counter change the dot will stay "on" for X seconds.

If you like the idea I will update this PR, and we can think on a better config gui for both

**Comment by DaveMDS** [comment]
Hi,
just pushed a second commit that implement the status icon "blinking",
let me know if you like it and if you have some better idea for the two labels 
in the config section.

let me know if you like it, I will then write the docs and perform a final commit.
...no other idea atm to improve this useful node :P

**Comment by eisbehr-** [comment]
Thnk you for the change. I have to check this before merge. But actually i have no time, so excuse me. But in fort sight it looks good!

**Comment by TTF5** [comment]
Hi,
it's been a year since the PR. Any Updates?
I would love this addition!

**Comment by dkern** [comment]
To be honest, no. 😞 

But it is truly nice to have. I merged it to an different branch to make some update, as for example the descriptions is still missing. I need to update this and then merge it to master. Will see if i get this done ... sorry for the delay. To many other things. 😉

**Comment by TTF5** [comment]
No problem! I'm grateful for your work! 😃

**Pull request merged**
